[graph]
# Only check Linux as that's all we care for
targets = ["x86_64-unknown-linux-gnu"]

[advisories]
version = 2
ignore = []
yanked = "deny"

[licenses]
version = 2
allow = ["MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "MPL-2.0", "Unicode-3.0"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[bans]
multiple-versions = "deny"
skip = [
    # tracing-subscriber depends on these older versions too, in some paths
    { name = "regex-automata", version = "0.1.10" },
    { name = "regex-syntax", version = "0.6.29" },
    # Old releases of rustix; 1.x still needs to tickle down the ecosystem
    { name = "rustix", version = "0.38.4" },
    { name = "linux-raw-sys", version = "0.4.15" },
]
